[package]
authors = ["Vigdail <vigdail.dev@gmail.com>"]
description = "In-memory key/value storage"
edition = "2018"
name = "kvs"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.15"

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"
